language: c
sudo: true
before_install: 
  - sudo apt-get update && sudo apt install -y nasm mtools curl build-essential
  - sudo apt-get -t unstable install libmpfr6
script:
  - source ./travis_scripts/download_dependecies.sh
  - ./configure.sh -w $TRAVIS_BUILD_DIR -t 1
  - ls
  - ./scripts/build.sh